-- 1) Drop old database (if you want a fresh start)
DROP DATABASE IF EXISTS business_db;

-- 2) Create and select the database
CREATE DATABASE IF NOT EXISTS business_db;
USE business_db;

-- 3) Create Employee table (no FKs)
CREATE TABLE Employee (
  EmployeeID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  JobTitle VARCHAR(50) NOT NULL,
  HireDate DATE NOT NULL,
  ModifiedDate DATETIME NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (EmployeeID)
) ENGINE=InnoDB;

-- 4) Create Product table (no FKs)
CREATE TABLE Product (
  ProductID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  ProductNumber VARCHAR(25) NOT NULL UNIQUE,
  ListPrice DECIMAL(10,2) NOT NULL,
  ModifiedDate DATETIME NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ProductID)
) ENGINE=InnoDB;

-- 5) Create Vendor table (no FKs)
CREATE TABLE Vendor (
  VendorID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  AccountNumber VARCHAR(15) NOT NULL UNIQUE,
  Name VARCHAR(50) NOT NULL,
  CreditRating TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PreferredVendorStatus TINYINT(1) NOT NULL DEFAULT 1,
  ActiveFlag TINYINT(1) NOT NULL DEFAULT 1,
  PurchasingWebServiceURL VARCHAR(255) DEFAULT NULL,
  ModifiedDate DATETIME NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (VendorID)
) ENGINE=InnoDB;

-- 6) Create ShipMethod table (no FKs)
CREATE TABLE ShipMethod (
  ShipMethodID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL UNIQUE,
  ShipBase DECIMAL(10,2) NOT NULL,
  ShipRate DECIMAL(10,2) NOT NULL,
  ModifiedDate DATETIME NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ShipMethodID)
) ENGINE=InnoDB;

-- 7) Create PurchaseOrderHeader table (no FKs)
CREATE TABLE PurchaseOrderHeader (
  PurchaseOrderID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  RevisionNumber TINYINT UNSIGNED NOT NULL DEFAULT 0,
  Status TINYINT UNSIGNED NOT NULL DEFAULT 1,
  EmployeeID INT UNSIGNED NOT NULL,
  VendorID INT UNSIGNED NOT NULL,
  ShipMethodID INT UNSIGNED NOT NULL,
  OrderDate DATE NOT NULL,
  ShipDate DATE DEFAULT NULL,
  SubTotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  TaxAmt DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Freight DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  TotalDue DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ModifiedDate DATETIME NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (PurchaseOrderID)
) ENGINE=InnoDB;

-- 8) Create PurchaseOrderDetail table (no FKs)
-- including the 'DueDate' column so it matches your CSV's 11 columns
CREATE TABLE PurchaseOrderDetail (
  PurchaseOrderID INT UNSIGNED NOT NULL,
  PurchaseOrderDetailID INT UNSIGNED NOT NULL,
  ProductID INT UNSIGNED NOT NULL,
  OrderQty INT NOT NULL,
  UnitPrice DECIMAL(10,2) NOT NULL,
  LineTotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ReceivedQty INT NOT NULL DEFAULT 0,
  RejectedQty INT NOT NULL DEFAULT 0,
  StockedQty INT NOT NULL DEFAULT 0,
  DueDate DATETIME NOT NULL,
  ModifiedDate DATETIME NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (PurchaseOrderID, PurchaseOrderDetailID)
) ENGINE=InnoDB;
